export enum AnimalFeedCategory {
  RED_MEAT = "Red Meat",
  WHITE_MEAT = "White Meat",
  FISH = "Fish",
  INSECTS = "Insects",
  HAY = "Hay",
  VEGETABLES = "Vegetables",
  FRUITS = "Fruits",
  GRAINS = "Grains",
  BROWSE = "Browse",
  PELLETS = "Pellets",
  NECTAR = "Nectar",
  SUPPLEMENTS = "Supplements",
  OTHERS = "Others",
}
