export enum AnimalFeedCategory {
  RED_MEAT = "RED_MEAT",
  WHITE_MEAT = "WHITE_MEAT",
  FISH = "FISH",
  INSECTS = "INSECTS",
  HAY = "HAY",
  VEGETABLES = "VEGETABLES",
  FRUITS = "FRUITS",
  GRAINS = "GRAINS",
  BROWSE = "BROWSE",
  PELLETS = "PELLETS",
  NECTAR = "NECTAR",
  SUPPLEMENTS = "SUPPLEMENTS",
  OTHERS = "OTHERS"
}