export enum ContinentEnum {
  AFRICA = "AFRICA",
  ASIA = "ASIA",
  EUROPE = "EUROPE",
  NORTH_AMERICA = "NORTH_AMERICA",
  OCEANIA = "OCEANIA",
  SOUTH_N_CENTRAL_AMERICA = "SOUTH_OR_CENTRAL_AMERICA",
}
