export enum FacilityLogType {
  ACTIVE_REPAIR_TICKET = "ACTIVE_REPAIR_TICKET",
  COMPLETED_REPAIR_TICKET = "COMPLETED_REPAIR_TICKET",
  MAINTENANCE_LOG = "MAINTENANCE_LOG",
  OPERATION_LOG = "OPERATION_LOG"
}
