export enum Reaction {
  POSITIVE_RESPONSE = "Positive Response",
  RESPONSIVE = "Responsive",
  ENTHUSIASTIC = "Enthusiastic",
  ENGAGED = "Engaged",
  PLAYFUL = "Playful",
  CONTENT = "Content",
  NEUTRAL_RESPONSE = "Neutral Response",
  OBSERVANT = "Observant",
  CAUTIOUS = "Cautious",
  NEGATIVE_RESPONSE = "Negative Response",
  STRESSED = "Stressed",
  AVOIDANT = "Avoidant",
  RESISTANT = "Resistant",
  AGGRESSIVE = "Aggressive",
  FEARFUL = "Fearful",
  OTHER_RESPONSE = "Other Response",
  ENERGETIC = "Energetic",
  RELAXED = "Relaxed",
  INDETERMINATE = "Indeterminate",
  UNDETERMINED = "Undetermined"
}